### ISSUE TITLE
The diablog box is crashing

### ISSUE THREAD

**Issue by NerosTie** [dimtion/Shaarlier#10]
Since the last version, when the dialog box shows up, it crashes few seconds later.
Not browser related, it crashes in the shaarlier app itself.
So, I can't 'shaare' something.

**Comment by dimtion** [comment]
Some questions : 
- Are you using the play-store version or the f-droid version ?
- Does it happen each time or just randomly ?
- Do you think it could come from the auto-loading of the title ? Try to disable auto-title in the settings, tell-me if it works better.
- Check in the settings that your account is correct, it is not impossible that the upgrade messed up the settings.
- To narrow down the problem : can you tell me if posting works when you disable the share dialog ?

Because you say it crashes few seconds after launch, I think this is because of a network related bug : either loading the tags or loading the title. 

If it is really a problem, while I figure out a solution, you can install an [older version](https://github.com/dimtion/Shaarlier/releases) but I understand that it is not really a confortable solution

**Comment by dimtion** [comment]
Could you try this release [Shaarlier v1.2.1](https://github.com/dimtion/Shaarlier/releases/tag/v1.2.1), and tell me if it works better and/or helps you with more error messages ?

**Comment by NerosTie** [comment]
- I tried every versions: same behaviour
- Each time
- I don't think it comes from the auto-loading title. If i disable it, same thing.
- Settings are correct
- It works if I disable the share dialog

I think it's Lollipop related, because Shaarlier is also installed on my tablet (Jelly Bean 4.1) and it works perfectlly.

Hm, I could try the version 1.2.1 but I don't know how to compile for Android :/

**Comment by dimtion** [comment]
Sorry, forgot to upload the apk. Have another [try](https://github.com/dimtion/Shaarlier/releases/tag/v1.2.1) ;)

**Comment by NerosTie** [comment]
Nothing change.

Actually, it works well just after the install then if I force quit the app, it will crashes every time even if I restart the smartphone.

**Comment by dimtion** [comment]
Would you mind if we continue on [gitter](https://gitter.im) ? It will be easier for sending debug apk...

**Comment by dimtion** [comment]
Should be finally fixed on [Shaarlier v1.2.2](https://github.com/dimtion/Shaarlier/releases/tag/v1.2.2) 

Thanks again Neros !

**Comment by NerosTie** [comment]
Thank you! :)
