### ISSUE TITLE
Add automatic description

### ISSUE THREAD

**Issue by NerosTie** [dimtion/Shaarlier#14]
It could be great to have an automatic description of the link by reading the content of the meta "description".  
Just like the title, but for the description.  
And, maybe, tags?

**Comment by dimtion** [comment]
Yes, retrieve some description from the the meta-data looks like a good idea. Perhaps adding a delete button on the description field would be helpful when the provided text is broken or unwanted.

About the tags, I was thinking of a good way of handling them : would the choice of tags be based on the shared url, on the sharing app or on key words in the description ? Maybe a mix of theses. It would also need a little rework of the tags field to delete them easily, indeed adding such automation would create a significant amount of unwanted tags. The problem is that each user has its own view of what a good tag is, and I would not be the one choosing for them.

**Comment by mro** [comment]
there's a lengthy thread over at https://github.com/shaarli/Shaarli/issues/322

description makes sense to me (https://github.com/mro/ShaarliOS), tags rather don't.

**Comment by dimtion** [comment]
Could you have a look at : https://github.com/dimtion/Shaarlier/releases/tag/v1.3.0-alpha

Please tell me if you have remarks or if you find any bug.

**Comment by NerosTie** [comment]
It works well!  

But more websites could be supported (because they don't use the classic meta description) if you add:

```
<meta property="og:description" content="" />
<meta name="twitter:description" content="" />
```

(plus, the `Settings` menu in the app, between `Share a link` and `Open my Shaarli`, is useless)

**Comment by dimtion** [comment]
Thanks for the feedback, I'll add them for the next release.

**Comment by mro** [comment]
see also at https://github.com/shaarli/Shaarli/issues/322#issuecomment-132253364

**Comment by dimtion** [comment]
Thanks @mro for the reminder (I have probably over read your comment...)

In shaarli/Shaarli#322 they don't mention `twitter:description` meta tag, what priority should be choose ? What about for example `og:description` > `twitter:description` > `description`) ?

**Comment by NerosTie** [comment]
@dimtion I think twitter must be the last because it's limited in every case or there are hashtags inside.

I would say : `description` > `og:description` > `twitter:description`  (og=opengraph=facebook)

But maybe I'm wrong!

**Comment by dimtion** [comment]
Yes you are right, but as @mro mentioned in https://github.com/shaarli/Shaarli/issues/322#issuecomment-132253364 `og:description` should probably be first.
