### ISSUE TITLE
Data is lost when switching to another app then coming back to Shaarlier

### ISSUE THREAD

**Issue by VLNTNO** [dimtion/Shaarlier#35]
Hi,

When I start filling in a shaare, then I switch to another app and then switch back to Shaarlier, the data is no longer available.

Is there a way to have data to persist the app switches?

**Comment by dimtion** [comment]
Hi,

Do you mean the data in the sharing form or that you already submited to Shaarli?

**Comment by immanuelfodor** [comment]
I think this is because of how Android works, you're in a share "intent" when editing the link in Shaarlier. The same happens when sharing from Gallery to Snapseed (for example), then switching apps, all your edits are lost in the picture editor because the content was shared into the other app. Really annoying, indeed :grinning:

**Comment by dimtion** [comment]
This issue was fixed in 99cbd9bfbf4206ef4a1b5f11c0ee740d76a675e5 and will be available in the next release.

**Comment by dimtion** [comment]
Update is live. I'm closing.
https://github.com/dimtion/Shaarlier/releases/tag/v1.8.0
