### ISSUE TITLE
Only obtain a title if the share intent doesn't provide one

### ISSUE THREAD

**Issue by lvuser** [dimtion/Shaarlier#8]
Currently the application goes to the website to obtain the title irrelevant of whether share intent provides one or not. Most of the android applications, when I share using the share intent, it provides a title as well. (E.g Firefox for Android, Sync for Reddit, Redreader).

it might be best to only obtain a title if the application didn't receive a title from the share intent. The Pindroid application ( https://code.google.com/p/pindroid/ ), which I use, only obtains a title if it didn't receive one.

I am not sure how many people might use it but you could always have a refresh button at the far end if the user wanted to get the title from the website rather than use the one obtained from share intent.

**Comment by dimtion** [comment]
Thanks for the suggestion. Indeed you are right, the thing is I already implemented something like that, and as you can see it doesn't work for many apps (currently Youtube App, SoundCloud...). In my defense it is the first app I develop so at the time I wrote that code I didn't know about the ShareCompact class which pindroid rightfully use for retrieving the title as well as the url.  [see](https://github.com/maxpower47/PinDroid/blob/5a9038ebd37c4de1f3ef398c99c5ec440629726f/app/src/main/java/com/pindroid/activity/SaveReadLaterBookmark.java#L81-82)
Thanks for the link, without it I would be stuck for a while without knowing such a class existed (because I wasn't looking for).  
About the refresh button, that is a great idea, do you think that if the intent doesn't provide any title, should the user press the "refresh" to get a title or the app should take the lead by downloading a default title ?

Thanks again :)

**Comment by lvuser** [comment]
Thank you for the android app. it is miles better than the previous two that I have used.

I am glad you found the link useful.

I think fetching the title automatically if the share intent didn't provide one, is the better way as users might not like the additional step of tapping the refresh button just to fetch the title. It also affects the user experience.

For advanced users, you could add an additional option in settings, like don't fetch the title automatically and by default it is unchecked. It depends on who you wanted to target the app for. Firefox for example has less options by default but advanced users can change many more things by going to about:config.

**Comment by dimtion** [comment]
Should be solved in the latest release.
